use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :guack, GuackWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :guack, Guack.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "hatsumei", # local dev user with minimal permissions
  password: "hatsu_devo",
  database: "guack_dev",
  hostname: "localhost",
  pool_size: 10


config :guack, Guack.Guardian,
  allowed_algos: ["HS512"],
  verify_module: Guardian.JWT,
  issuer: "Guack",
  ttl: [30, :days],
  allowed_drift: 2000,
  verify_issuer: true,
  serializer: Guack.Guardian,
  secret_key: "/snVj3Y3turjDDT8exjg7ujm6xRV2C3NFdiPYcb+Ekrj1xeU5flOeL0vn2HiV+Om"
